import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import rateLimit from "express-rate-limit";
import { z } from "zod";
import { callAI, streamAI, checkAIProxyHealth, type ChatMessage, type CallAIOptions } from "./server/services/aiClient";
import { createAIKey, deleteAIKey, exportAIKeyBackup, getAIVaultSecurityStatus, getSupportedAIProviders, importAIKeyBackup, listAIKeys, lockAIVault, setupAIVaultPassphrase, unlockAIVault, updateAIKey } from "./server/services/aiKeyVault";
import { diagnoseAIRouter, testAIKey } from "./server/services/aiRouter";
import { runAIPreflight } from "./server/services/aiDoctor";
import { clearAIUsageLogs, readAIUsageLogs } from "./server/services/aiUsageLog";
import { disarmAIVaultAutoLock, getAIVaultAutoLockStatus, markAIVaultActivity, updateAIVaultAutoLockConfig } from "./server/services/aiVaultAutoLock";
import { appendIntegrationEvent, clearIntegrationEvents, listIntegrationConnectors, readIntegrationEvents, testIntegrationConnector, updateIntegrationConnector } from "./server/services/integrationRegistry";
import { createGitHubIssue, getGitHubSummary } from "./server/services/githubConnector";

dotenv.config();

const databaseSaveSchema = z.object({ payload: z.record(z.string(), z.any()) });
const geminiGenerateSchema = z.object({ prompt: z.string().min(1, "Prompt cannot be empty"), model: z.string().optional(), history: z.array(z.object({ role: z.enum(["user", "model"]), text: z.string().optional() })).optional(), systemInstruction: z.string().optional(), file: z.object({ data: z.string(), mimeType: z.string() }).optional() });
const aiProviderSchema = z.enum(["gemini", "groq", "openrouter", "anthropic", "ollama"]);
const aiKeyCreateSchema = z.object({ provider: aiProviderSchema, label: z.string().optional(), apiKey: z.string().optional(), model: z.string().optional(), baseUrl: z.string().optional(), priority: z.number().optional(), enabled: z.boolean().optional() });
const aiKeyUpdateSchema = aiKeyCreateSchema.partial().extend({ lastStatus: z.enum(["ok", "error", "quota", "untested"]).optional(), lastError: z.string().optional() });
const aiBackupExportSchema = z.object({ passphrase: z.string().min(8, "Mật khẩu backup phải có ít nhất 8 ký tự.") });
const aiBackupImportSchema = z.object({ passphrase: z.string().min(8, "Mật khẩu backup phải có ít nhất 8 ký tự."), mode: z.enum(["merge", "replace"]).default("merge"), backup: z.object({ version: z.literal(1), app: z.literal("LedgerFlow Studio"), exportedAt: z.string(), kdf: z.literal("scrypt"), cipher: z.literal("aes-256-gcm"), salt: z.string(), iv: z.string(), tag: z.string(), payload: z.string(), note: z.string() }) });
const aiVaultPassphraseSchema = z.object({ passphrase: z.string().min(8, "Mật khẩu AI Vault phải có ít nhất 8 ký tự.") });
const aiVaultAutoLockSchema = z.object({ enabled: z.boolean().optional(), timeoutMinutes: z.number().min(1).max(1440).optional() });
const integrationPatchSchema = z.object({ enabled: z.boolean().optional(), status: z.enum(["connected", "local", "manual", "planned", "error"]).optional(), priority: z.enum(["P0", "P1", "P2", "P3"]).optional(), url: z.string().optional(), localCommand: z.string().optional(), notes: z.string().optional() });
const integrationEventSchema = z.object({ type: z.enum(["status", "test", "config", "handoff", "note"]).default("note"), level: z.enum(["info", "success", "warning", "error"]).default("info"), message: z.string().min(1) });
const githubIssueSchema = z.object({ repo: z.string().optional(), title: z.string().min(3, "Tiêu đề issue phải có ít nhất 3 ký tự."), body: z.string().optional(), labels: z.array(z.string()).optional() });
type GeminiGenerateInput = z.infer<typeof geminiGenerateSchema>;

function getSimulatedMarketSurveyResponse(niche: string, direction?: string) { return { summary: `Mô phỏng nghiên cứu thị trường cho: ${niche}.`, metrics: { pricingPreferred: [], painPoints: [], channels: [] }, personas: [], gaps: [], competitors: [], blueprint: { direction: direction || "B2D Tool" }, sources: [{ title: "Fallback simulator", url: "local" }] }; }
function resolveProxyModel(model?: string): NonNullable<CallAIOptions["model"]> { if (!model) return "ai-assistant"; const normalized = model.toLowerCase(); return normalized.includes("pro") || normalized.includes("3.5") || normalized.includes("advanced") ? "ai-assistant-pro" : "ai-assistant"; }
function buildAIMessages({ prompt, history, systemInstruction, file }: GeminiGenerateInput): ChatMessage[] { const messages: ChatMessage[] = []; if (systemInstruction) messages.push({ role: "system", content: systemInstruction }); if (history) for (const msg of history) if (msg.text) messages.push({ role: msg.role === "user" ? "user" : "assistant", content: msg.text }); messages.push({ role: "user", content: file ? `${prompt}\n\n[Attached ${file.mimeType} as base64; current text gateway does not parse binary content directly.]` : prompt }); return messages; }
function isRateLimitOrQuotaError(err: any): boolean { const text = `${err?.status || ""} ${err?.message || ""} ${JSON.stringify(err?.body || {})}`.toLowerCase(); return text.includes("429") || text.includes("quota") || text.includes("resource_exhausted") || text.includes("rate limit") || text.includes("too many requests"); }

async function startServer() {
  const app = express();
  const PORT = Number(process.env.PORT ?? 3000);
  app.set("trust proxy", 1);
  app.use(express.json({ limit: "15mb" }));
  app.use(express.urlencoded({ extended: true, limit: "15mb" }));
  app.use((req, res, next) => { const allowedOrigins = ["http://localhost:3000", "http://127.0.0.1:3000", "http://0.0.0.0:3000"]; const origin = req.headers.origin; if (origin) { const isAllowed = allowedOrigins.includes(origin) || origin.endsWith(".run.app") || /https:\/\/ais-.*\.run\.app/.test(origin); if (isAllowed) res.setHeader("Access-Control-Allow-Origin", origin); } res.setHeader("Access-Control-Allow-Methods", "GET,POST,PATCH,PUT,DELETE,OPTIONS"); res.setHeader("Access-Control-Allow-Headers", "Content-Type,Authorization"); if (req.method === "OPTIONS") res.sendStatus(204); else next(); });
  const apiLimiter = rateLimit({ windowMs: 60_000, max: 30, message: { error: "Bạn đã đạt giới hạn yêu cầu/phút. Vui lòng thử lại sau.", isRateLimit: true }, standardHeaders: true, legacyHeaders: false, validate: { trustProxy: false } });
  app.use("/api/gemini/", apiLimiter); app.use("/api/ai/", apiLimiter); app.use("/api/integrations/", apiLimiter);
  app.get("/api/health", (req, res) => res.json({ status: "ok", time: new Date() }));

  const STORAGE_FILE = path.join(process.cwd(), "db_storage.json");
  app.get("/api/db/load", async (req, res) => { try { if (!fs.existsSync(STORAGE_FILE)) return res.json({ success: true, data: {} }); res.json({ success: true, data: JSON.parse(await fs.promises.readFile(STORAGE_FILE, "utf-8")) }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to load database state." }); } });
  app.post("/api/db/save", async (req, res) => { try { const parsed = databaseSaveSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); await fs.promises.writeFile(STORAGE_FILE, JSON.stringify(parsed.data.payload, null, 2), "utf-8"); res.json({ success: true, message: "Database synchronized successfully on the server." }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to save database state." }); } });

  app.get("/api/integrations", async (req, res) => { try { res.json({ success: true, connectors: await listIntegrationConnectors(), events: await readIntegrationEvents(30) }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to list integrations." }); } });
  app.patch("/api/integrations/:id", async (req, res) => { try { const parsed = integrationPatchSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); res.json({ success: true, connector: await updateIntegrationConnector(req.params.id, parsed.data) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to update integration." }); } });
  app.post("/api/integrations/:id/test", async (req, res) => { try { res.json({ success: true, connector: await testIntegrationConnector(req.params.id), events: await readIntegrationEvents(30) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to test integration." }); } });
  app.post("/api/integrations/:id/events", async (req, res) => { try { const parsed = integrationEventSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); res.json({ success: true, event: await appendIntegrationEvent({ connectorId: req.params.id, ...parsed.data }) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to append integration event." }); } });
  app.get("/api/integrations/events", async (req, res) => { try { res.json({ success: true, events: await readIntegrationEvents(Number(req.query.limit ?? 100)) }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to read integration events." }); } });
  app.delete("/api/integrations/events", async (req, res) => { try { await clearIntegrationEvents(); res.json({ success: true }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to clear integration events." }); } });
  app.get("/api/integrations/github/summary", async (req, res) => { try { const summary = await getGitHubSummary(typeof req.query.repo === "string" ? req.query.repo : undefined); await appendIntegrationEvent({ connectorId: "github", type: "test", level: "success", message: `GitHub summary loaded for ${summary.repo}.` }); res.json({ success: true, summary }); } catch (err: any) { await appendIntegrationEvent({ connectorId: "github", type: "test", level: "error", message: err.message || "GitHub summary failed." }).catch(() => undefined); res.status(400).json({ success: false, error: err.message || "Failed to load GitHub summary." }); } });
  app.post("/api/integrations/github/issues", async (req, res) => { try { const parsed = githubIssueSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); const issue = await createGitHubIssue(parsed.data); await appendIntegrationEvent({ connectorId: "github", type: "handoff", level: "success", message: `Created GitHub issue #${issue.number}: ${issue.title}` }); res.json({ success: true, issue }); } catch (err: any) { await appendIntegrationEvent({ connectorId: "github", type: "handoff", level: "error", message: err.message || "Create GitHub issue failed." }).catch(() => undefined); res.status(400).json({ success: false, error: err.message || "Failed to create GitHub issue." }); } });

  app.get("/api/ai/providers", (req, res) => res.json({ success: true, providers: getSupportedAIProviders() }));
  app.get("/api/ai/vault/status", async (req, res) => { try { res.json({ success: true, vault: await getAIVaultSecurityStatus(), autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to read AI vault status." }); } });
  app.get("/api/ai/vault/auto-lock", async (req, res) => { try { res.json({ success: true, autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to read AI vault auto-lock status." }); } });
  app.patch("/api/ai/vault/auto-lock", async (req, res) => { try { const parsed = aiVaultAutoLockSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); res.json({ success: true, autoLock: await updateAIVaultAutoLockConfig(parsed.data) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to update AI vault auto-lock." }); } });
  app.post("/api/ai/vault/passphrase", async (req, res) => { try { const parsed = aiVaultPassphraseSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); const vault = await setupAIVaultPassphrase(parsed.data.passphrase); await markAIVaultActivity("setup-passphrase"); res.json({ success: true, vault, autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to set AI vault passphrase." }); } });
  app.post("/api/ai/vault/unlock", async (req, res) => { try { const parsed = aiVaultPassphraseSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); const vault = await unlockAIVault(parsed.data.passphrase); await markAIVaultActivity("manual-unlock"); res.json({ success: true, vault, autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to unlock AI vault." }); } });
  app.post("/api/ai/vault/lock", async (req, res) => { try { disarmAIVaultAutoLock(); res.json({ success: true, vault: await lockAIVault(), autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to lock AI vault." }); } });
  app.get("/api/ai/keys", async (req, res) => { try { res.json({ success: true, keys: await listAIKeys(), vault: await getAIVaultSecurityStatus(), autoLock: await getAIVaultAutoLockStatus() }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to list AI keys." }); } });
  app.post("/api/ai/keys", async (req, res) => { try { const parsed = aiKeyCreateSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("create-key"); res.json({ success: true, key: await createAIKey(parsed.data) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to create AI key." }); } });
  app.patch("/api/ai/keys/:id", async (req, res) => { try { const parsed = aiKeyUpdateSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("update-key"); res.json({ success: true, key: await updateAIKey(req.params.id, parsed.data) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to update AI key." }); } });
  app.delete("/api/ai/keys/:id", async (req, res) => { try { await markAIVaultActivity("delete-key"); res.json({ success: true, deleted: await deleteAIKey(req.params.id) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to delete AI key." }); } });
  app.post("/api/ai/keys/test", async (req, res) => { const parsed = aiKeyCreateSchema.pick({ provider: true, apiKey: true, model: true, baseUrl: true }).safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); const result = await testAIKey(parsed.data); res.status(result.success ? 200 : 400).json({ ...result, ok: result.success, status: result.success ? "ok" : "error" }); });
  app.get("/api/ai/diagnostics", async (req, res) => { try { await markAIVaultActivity("diagnostics"); const diagnostics = await diagnoseAIRouter(); res.json({ success: true, diagnostics, results: diagnostics.results }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to diagnose AI router." }); } });
  app.get("/api/ai/preflight", async (req, res) => { try { res.json({ success: true, report: await runAIPreflight() }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to run AI preflight." }); } });
  app.get("/api/ai/logs", async (req, res) => { try { const limit = Number(req.query.limit ?? 100); res.json({ success: true, logs: await readAIUsageLogs(limit) }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to read AI usage logs." }); } });
  app.delete("/api/ai/logs", async (req, res) => { try { await clearAIUsageLogs(); res.json({ success: true }); } catch (err: any) { res.status(500).json({ success: false, error: err.message || "Failed to clear AI usage logs." }); } });
  app.post("/api/ai/backup/export", async (req, res) => { try { const parsed = aiBackupExportSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("export-backup"); res.json({ success: true, backup: await exportAIKeyBackup(parsed.data.passphrase) }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to export AI key backup." }); } });
  app.post("/api/ai/backup/import", async (req, res) => { try { const parsed = aiBackupImportSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("import-backup"); const result = await importAIKeyBackup(parsed.data.backup, parsed.data.passphrase, parsed.data.mode); res.json({ success: true, ...result }); } catch (err: any) { res.status(400).json({ success: false, error: err.message || "Failed to import AI key backup." }); } });

  app.get("/api/gemini/status", async (req, res) => { const keys = await listAIKeys().catch(() => []); const vault = await getAIVaultSecurityStatus().catch(() => undefined); const autoLock = await getAIVaultAutoLockStatus().catch(() => undefined); const routerHealthy = await checkAIProxyHealth(); res.json({ success: true, usingCustomKey: keys.length > 0, keyName: keys.length > 0 ? `AI Key Vault (${keys.filter(k => k.enabled).length}/${keys.length} enabled)` : "No local AI keys configured", isProReady: routerHealthy && !vault?.isLocked, localKeyCount: keys.length, enabledKeyCount: keys.filter(k => k.enabled).length, vault, autoLock }); });
  app.post("/api/gemini/generate", async (req, res) => { try { const parsed = geminiGenerateSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("ai-generate"); const response = await callAI(buildAIMessages(parsed.data), { model: resolveProxyModel(parsed.data.model) }); await markAIVaultActivity("ai-generate-complete"); res.json({ success: true, text: response.content, modelUsed: response.modelUsed }); } catch (err: any) { const isQuota = isRateLimitOrQuotaError(err); res.status(isQuota ? 400 : 500).json({ success: false, isMissingKey: isQuota, error: err.message || "An error occurred during generation." }); } });
  app.post("/api/gemini/market-survey", async (req, res) => { try { const { niche } = req.body; const targetNiche = niche || "Phần mềm quản trị B2D hoặc Kế toán SME Việt Nam"; const prompt = `Return JSON only for market research about ${targetNiche}. Schema: summary, metrics, personas, gaps, competitors, blueprint, sources.`; await markAIVaultActivity("market-survey"); const response = await callAI([{ role: "user", content: prompt }], { model: "ai-assistant-pro", temperature: 0.2 }); await markAIVaultActivity("market-survey-complete"); const text = (response.content || "").replace(/```json/g, "").replace(/```/g, "").trim(); const match = text.match(/\{[\s\S]*\}/); const data = JSON.parse(match ? match[0] : text); data.modelUsed = response.modelUsed; res.json({ success: true, data }); } catch (err: any) { const { niche, selectedDirection } = req.body; res.json({ success: true, isSimulatedFallback: true, error: err.message, data: getSimulatedMarketSurveyResponse(niche || "Phần mềm B2D / Kế toán SME Việt Nam", selectedDirection) }); } });
  app.post("/api/gemini/stream", async (req, res) => { try { const parsed = geminiGenerateSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: parsed.error.issues.map(i => i.message).join(", ") }); await markAIVaultActivity("ai-stream"); res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache"); res.setHeader("Connection", "keep-alive"); res.setHeader("X-Accel-Buffering", "no"); res.flushHeaders(); for await (const text of streamAI(buildAIMessages(parsed.data), { model: resolveProxyModel(parsed.data.model) })) if (text) res.write(`data: ${JSON.stringify({ text })}\n\n`); await markAIVaultActivity("ai-stream-complete"); res.write("data: [DONE]\n\n"); res.end(); } catch (err: any) { if (!res.headersSent) return res.status(400).json({ isMissingKey: isRateLimitOrQuotaError(err), error: err.message || "An error occurred during streaming." }); res.write(`data: ${JSON.stringify({ error: err.message || "An error occurred during streaming." })}\n\n`); res.end(); } });

  if (process.env.NODE_ENV !== "production") { const vite = await createViteServer({ server: { middlewareMode: true }, appType: "spa" }); app.use(vite.middlewares); } else { const distPath = path.join(process.cwd(), "dist"); app.use(express.static(distPath)); app.get("*", (req, res) => res.sendFile(path.join(distPath, "index.html"))); }
  app.listen(PORT, "0.0.0.0", () => { console.log(`Server running on http://0.0.0.0:${PORT}`); console.log("AI Settings UI: http://127.0.0.1:3000/ai-settings.html"); });
}
startServer();
