type WorkspaceSubtabAliasMap = Record<string, Record<string, string>>;

export const WORKSPACE_SUBTAB_ALIASES: WorkspaceSubtabAliasMap = {
  ceo_command: {
    brief: 'overview',
    standup: 'today',
    daily: 'today',
    weekly: 'today',
    knowledge: 'today',
    sop_risk: 'today',
    sop: 'today',
    risk: 'today',
    command_center: 'autonomous_command',
    autonomous: 'autonomous_command',
    founder_rhythm: 'standup_rhythm',
    rhythm: 'standup_rhythm',
  },
  knowledge_library: {
    knowledge: 'library',
    company_memory: 'library',
    memory: 'library',
    operating_layer: 'operating_layer',
    operating_knowledge: 'operating_layer',
    rag: 'rag_simulator',
    rag_sandbox: 'rag_simulator',
    vector_search: 'rag_simulator',
  },
  product_studio: {
    ideas_moat: 'portfolio',
    dev_hub: 'portfolio',
    tasks_progress: 'portfolio',
    roadmap: 'portfolio',
    strategy: 'portfolio',
    launch_readiness: 'portfolio',
    deploy: 'portfolio',
    logistics: 'portfolio',
    game_studio: 'games_ml',
    game_ml: 'games_ml',
    games: 'games_ml',
    game_builder: 'game_builder',
    smoke_test: 'smoke_test',
    vaporware: 'smoke_test',
  },
  marketing_growth: {
    growth_marketing: 'campaigns',
    campaign_lab: 'campaigns',
    campaign_funnel: 'campaigns',
    rollout_qa: 'campaigns',
    market_research: 'campaigns',
    content_zalo: 'content',
    video_creator: 'content',
    video_lab: 'content',
  },
  sales_crm: {
    leads_outreach: 'funnel_lab',
    sales_pipeline: 'funnel_lab',
    lead_scoring: 'funnel_lab',
    funnel: 'funnel_lab',
    pipeline: 'funnel_lab',
    pricing_lab: 'pricing_ltv',
    pricing: 'pricing_ltv',
    pricing_retention: 'pricing_ltv',
    ltv: 'pricing_ltv',
    ltv_nps: 'referral_nps',
    nps: 'referral_nps',
    affiliate: 'referral_nps',
    followup: 'referral_nps',
    retention_partners: 'referral_nps',
  },
  growth_sales: {
    campaign_lab: 'dashboard',
    rollout_qa: 'dashboard',
    content_zalo: 'content_studio',
    video_lab: 'content_studio',
    leads_outreach: 'sales_crm',
    ltv_nps: 'retention_partners',
    affiliate: 'retention_partners',
    pricing_lab: 'dashboard',
  },
  finance_accounting: {
    revenue: 'cashflow',
    founder_review: 'cashflow',
    runway_advisory: 'cashflow',
    advisory: 'founder_control',
    board_report: 'founder_control',
    founder_control: 'founder_control',
    coso: 'audit',
    audit_control: 'audit',
    internal_audit: 'audit',
    tax: 'tax_simulator',
    tax_audit: 'tax_simulator',
  },
  operations: {
    ideas_moat: 'product_studio',
    dev_hub: 'product_studio',
    tasks_progress: 'product_studio',
    roadmap: 'product_studio',
    deploy: 'logistics',
    supply_chain: 'logistics',
    procurement: 'logistics',
    campaign_lab: 'growth_marketing',
    campaign_funnel: 'growth_marketing',
    rollout_qa: 'growth_marketing',
    content_zalo: 'growth_marketing',
    video_creator: 'growth_marketing',
    video_lab: 'growth_marketing',
    market_research: 'growth_marketing',
    leads_outreach: 'sales_crm',
    ltv_nps: 'sales_crm',
    affiliate: 'sales_crm',
    pricing_lab: 'sales_crm',
  },
  analytics: {
    python_sql: 'python_sandbox',
    python_sql_datascience: 'python_sandbox',
    datascience: 'data',
    financial_ds: 'data',
    data_science: 'data',
    financial_charts: 'data',
    observability: 'observability',
    ai_observability: 'observability',
    market_research: 'market_models',
    market_survey: 'market_models',
    ml_applied: 'market_models',
    browser_sim: 'automation_planner',
    automation_planner: 'automation_planner',
    ai_game_studio: '3d_lab',
    game_studio: '3d_lab',
    game_ml: '3d_lab',
    prompt_labs: 'prompt_lab',
    prompt_lab: 'prompt_lab',
    gemini_playground: 'gemini_lab',
    gemini: 'gemini_lab',
    data_engineering: 'data_engineering',
    deploy_business: 'deploy_lab',
    deploy_lab: 'deploy_lab',
    decision_memory: 'decision_memory',
    founder_labs: 'founder_labs',
    labs: 'founder_labs',
  },
  ai_factory: {
    overview: 'command',
    ai_ops: 'command',
    command_center: 'command',
    governance: 'governance',
    advanced: 'governance',
    agent_builder: 'agent_builder',
    agent_assembly: 'agent_builder',
    daemon: 'missions',
    mobile: 'missions',
    runtime: 'missions',
    mission_queue: 'missions',
    runbook: 'missions',
    mission_templates: 'mission_templates',
    audit_trace: 'mission_audit',
    mission_audit: 'mission_audit',
    release_gate: 'mission_release',
    release_ops: 'mission_release',
    snapshot_export: 'mission_release',
    review_notes: 'mission_release',
    staff_roles: 'command',
    staff_assistants: 'assistant',
    agents: 'assistant',
    staff_assignment: 'tasks',
    assignment: 'tasks',
    people: 'command',
    memory_rag: 'memory_rag',
    knowledge_content: 'memory_rag',
    prompt_labs: 'assistant',
    robot_lab: 'robot_lab',
    robot_auto: 'automation',
    automation_rules: 'automation',
    automations: 'automation',
    browser_sim: 'automation',
    robot_bridge: 'automation',
    automation_health: 'automation',
    tool_catalog: 'tool_catalog',
    skill_directory: 'skills',
    skill_invocation: 'skills',
    patch_review: 'mission_release',
    patch_safety: 'mission_release',
    labs_diagnostics: 'dispatch_matrix',
    openclaw: 'dispatch_matrix',
    tools_security: 'dispatch_matrix',
    security: 'dispatch_matrix',
    software_factory: 'automation',
    factory: 'automation',
    factory_runtime: 'automation',
    factory_health: 'automation',
    factory_commands: 'automation',
  },
  ai_staff_sandbox: {
    staff_assistants: 'agents',
    ai_ops: 'overview',
    robot_lab: 'automations',
    automation_rules: 'automations',
    prompt_labs: 'knowledge_prompts',
    project_memory: 'knowledge_prompts',
    python_sql: 'labs',
    browser_sim: 'automations',
    financial_ds: 'labs',
    ai_game_studio: 'labs',
    simulation: 'labs',
  },
  system_settings: {
    ai_gateway: 'general',
    integrations: 'integrations',
    connections: 'hybrid_connectors',
    hybrid: 'hybrid_connectors',
    hybrid_connectors: 'hybrid_connectors',
    github: 'hybrid_connectors',
    local_tools: 'hybrid_connectors',
    web_ai: 'hybrid_connectors',
    user_roles: 'general',
    permissions: 'general',
    audit: 'security_audit',
    backup_data: 'general',
    security: 'security_audit',
    config_health: 'hybrid_connectors',
    rollback: 'recovery_ops',
    build_monitor: 'devops',
    merge_readiness: 'devops',
    pr_control: 'devops',
    patch_diff: 'patch_review',
    patch_review: 'patch_review',
    sandbox_patch: 'patch_review',
    ci_recovery: 'recovery_ops',
    ci_run: 'recovery_ops',
    dev_handoff: 'release_factory',
    ci_doctor: 'devops',
    release_artifact: 'release_factory',
    approved_pr: 'git_ops',
    git_ops: 'git_ops',
    git_assistant: 'git_ops',
    approvals: 'devops',
    artifact_inspector: 'release_factory',
    backup_restore: 'general',
    emergency_stop: 'general',
    software_factory: 'release_factory',
    release_factory: 'release_factory',
    security_audit: 'security_audit',
  },
};

export function resolveWorkspaceSubTab(
  workspaceId: string,
  requestedSubTabId: string | undefined,
  validSubTabIds: readonly string[],
): string | undefined {
  if (!requestedSubTabId) return undefined;
  if (validSubTabIds.includes(requestedSubTabId)) return requestedSubTabId;

  const alias = WORKSPACE_SUBTAB_ALIASES[workspaceId]?.[requestedSubTabId];
  if (alias && validSubTabIds.includes(alias)) return alias;

  return undefined;
}
