type WorkspaceSubtabAliasMap = Record<string, Record<string, string>>;

export const WORKSPACE_SUBTAB_ALIASES: WorkspaceSubtabAliasMap = {
  ceo_command: {
    overview: 'brief',
    standup: 'daily_weekly',
    daily: 'daily_weekly',
    weekly: 'daily_weekly',
    knowledge: 'library',
    sop_risk: 'sop_rd',
    sop: 'sop_rd',
    risk: 'sop_rd',
  },
  product_studio: {
    ideas_moat: 'portfolio',
    dev_hub: 'portfolio',
    tasks_progress: 'delivery',
    roadmap: 'portfolio',
    strategy: 'portfolio',
    launch_readiness: 'delivery',
    deploy: 'delivery',
    logistics: 'delivery',
    game_studio: 'portfolio',
  },
  marketing_growth: {
    growth_marketing: 'campaigns',
    campaign_lab: 'campaigns',
    campaign_funnel: 'campaigns',
    rollout_qa: 'campaigns',
    market_research: 'campaigns',
    content_zalo: 'content',
    video_creator: 'content',
    video_lab: 'content',
  },
  sales_crm: {
    leads_outreach: 'pipeline',
    sales_pipeline: 'pipeline',
    lead_scoring: 'pipeline',
    pricing_lab: 'pricing_retention',
    pricing: 'pricing_retention',
    ltv_nps: 'pricing_retention',
    nps: 'pricing_retention',
    affiliate: 'pricing_retention',
    retention_partners: 'pricing_retention',
  },
  growth_sales: {
    campaign_lab: 'dashboard',
    rollout_qa: 'dashboard',
    content_zalo: 'content_studio',
    video_lab: 'content_studio',
    leads_outreach: 'sales_crm',
    ltv_nps: 'retention_partners',
    affiliate: 'retention_partners',
    pricing_lab: 'dashboard',
  },
  finance_accounting: {
    revenue: 'cashflow',
    founder_review: 'cashflow',
    runway_advisory: 'cashflow',
    coso: 'audit',
    audit_control: 'audit',
  },
  operations: {
    ideas_moat: 'product_studio',
    dev_hub: 'product_studio',
    tasks_progress: 'product_studio',
    roadmap: 'product_studio',
    deploy: 'logistics',
    supply_chain: 'logistics',
    procurement: 'logistics',
    campaign_lab: 'growth_marketing',
    campaign_funnel: 'growth_marketing',
    rollout_qa: 'growth_marketing',
    content_zalo: 'growth_marketing',
    video_creator: 'growth_marketing',
    video_lab: 'growth_marketing',
    market_research: 'growth_marketing',
    leads_outreach: 'sales_crm',
    ltv_nps: 'sales_crm',
    affiliate: 'sales_crm',
    pricing_lab: 'sales_crm',
  },
  analytics: {
    python_sql: 'python_sandbox',
    python_sql_datascience: 'python_sandbox',
    datascience: 'data_science',
    financial_ds: 'data_science',
    ai_game_studio: 'game_studio',
    game_ml: 'game_studio',
    simulation: 'game_studio',
    prompt_labs: 'gemini_playground',
  },
  ai_factory: {
    overview: 'command',
    ai_ops: 'command',
    command_center: 'command',
    governance: 'advanced',
    daemon: 'advanced',
    mobile: 'advanced',
    runtime: 'missions',
    mission_queue: 'missions',
    runbook: 'missions',
    audit_trace: 'missions',
    release_gate: 'missions',
    snapshot_export: 'missions',
    review_notes: 'missions',
    staff_roles: 'advanced',
    staff_assistants: 'advanced',
    agents: 'advanced',
    people: 'advanced',
    memory_rag: 'advanced',
    knowledge_content: 'advanced',
    prompt_labs: 'advanced',
    robot_lab: 'robot_auto',
    automation_rules: 'robot_auto',
    automations: 'robot_auto',
    browser_sim: 'robot_auto',
    robot_bridge: 'robot_auto',
    automation_health: 'robot_auto',
    tool_catalog: 'advanced',
    skill_directory: 'advanced',
    skill_invocation: 'advanced',
    patch_review: 'advanced',
    patch_safety: 'advanced',
    labs_diagnostics: 'advanced',
    openclaw: 'advanced',
    tools_security: 'advanced',
    security: 'advanced',
    software_factory: 'advanced',
    factory: 'advanced',
    factory_runtime: 'advanced',
    factory_health: 'advanced',
    factory_commands: 'advanced',
  },
  ai_staff_sandbox: {
    staff_assistants: 'agents',
    ai_ops: 'overview',
    robot_lab: 'automations',
    automation_rules: 'automations',
    prompt_labs: 'knowledge_prompts',
    project_memory: 'knowledge_prompts',
    python_sql: 'labs',
    browser_sim: 'automations',
    financial_ds: 'labs',
    ai_game_studio: 'labs',
    simulation: 'labs',
  },
  system_settings: {
    ai_gateway: 'general',
    integrations: 'general',
    connections: 'general',
    user_roles: 'general',
    permissions: 'safety_gates',
    audit: 'control',
    backup_data: 'control',
    security: 'control',
    config_health: 'control',
    rollback: 'control',
    build_monitor: 'devops',
    merge_readiness: 'devops',
    pr_control: 'devops',
    patch_diff: 'devops',
    sandbox_patch: 'devops',
    ci_recovery: 'devops',
    ci_run: 'devops',
    dev_handoff: 'devops',
    ci_doctor: 'devops',
    release_artifact: 'safety_gates',
    approved_pr: 'safety_gates',
    approvals: 'safety_gates',
    artifact_inspector: 'safety_gates',
    backup_restore: 'safety_gates',
    emergency_stop: 'emergency',
  },
};

export function resolveWorkspaceSubTab(
  workspaceId: string,
  requestedSubTabId: string | undefined,
  validSubTabIds: readonly string[],
): string | undefined {
  if (!requestedSubTabId) return undefined;
  if (validSubTabIds.includes(requestedSubTabId)) return requestedSubTabId;

  const alias = WORKSPACE_SUBTAB_ALIASES[workspaceId]?.[requestedSubTabId];
  if (alias && validSubTabIds.includes(alias)) return alias;

  return undefined;
}
