type WorkspaceSubtabAliasMap = Record<string, Record<string, string>>;

export const WORKSPACE_SUBTAB_ALIASES: WorkspaceSubtabAliasMap = {
  ceo_command: {
    brief: 'overview',
    standup: 'today',
    daily: 'today',
    weekly: 'today',
    knowledge: 'today',
    sop_risk: 'today',
    sop: 'today',
    risk: 'today',
    command_center: 'autonomous_command',
    autonomous: 'autonomous_command',
    founder_rhythm: 'standup_rhythm',
    rhythm: 'standup_rhythm',
  },
  knowledge_library: {
    knowledge: 'library',
    company_memory: 'library',
    memory: 'library',
    operating_layer: 'operating_layer',
    operating_knowledge: 'operating_layer',
    rag: 'rag_simulator',
    rag_sandbox: 'rag_simulator',
    vector_search: 'rag_simulator',
  },
  product_studio: {
    ideas_moat: 'portfolio',
    dev_hub: 'portfolio',
    tasks_progress: 'portfolio',
    roadmap: 'portfolio',
    strategy: 'portfolio',
    launch_readiness: 'portfolio',
    deploy: 'portfolio',
    logistics: 'portfolio',
    game_studio: 'games_ml',
    game_ml: 'games_ml',
    games: 'games_ml',
    game_builder: 'game_builder',
    smoke_test: 'smoke_test',
    vaporware: 'smoke_test',
  },
  marketing_growth: {
    growth_marketing: 'campaigns',
    campaign_lab: 'campaigns',
    campaign_funnel: 'campaigns',
    rollout_qa: 'campaigns',
    market_research: 'campaigns',
    content_zalo: 'content',
    video_creator: 'content',
    video_lab: 'content',
  },
  sales_crm: {
    leads_outreach: 'funnel_lab',
    sales_pipeline: 'funnel_lab',
    lead_scoring: 'funnel_lab',
    funnel: 'funnel_lab',
    pipeline: 'funnel_lab',
    pricing_lab: 'pricing_ltv',
    pricing: 'pricing_ltv',
    pricing_retention: 'pricing_ltv',
    ltv: 'pricing_ltv',
    ltv_nps: 'referral_nps',
    nps: 'referral_nps',
    affiliate: 'referral_nps',
    followup: 'referral_nps',
    retention_partners: 'referral_nps',
  },
  growth_sales: {
    campaign_lab: 'dashboard',
    rollout_qa: 'dashboard',
    content_zalo: 'content_studio',
    video_lab: 'content_studio',
    leads_outreach: 'sales_crm',
    ltv_nps: 'retention_partners',
    affiliate: 'retention_partners',
    pricing_lab: 'dashboard',
  },
  finance_accounting: {
    revenue: 'cashflow',
    founder_review: 'cashflow',
    runway_advisory: 'cashflow',
    advisory: 'founder_control',
    board_report: 'founder_control',
    founder_control: 'founder_control',
    coso: 'audit',
    audit_control: 'audit',
    internal_audit: 'audit',
    tax: 'tax_simulator',
    tax_audit: 'tax_simulator',
  },
  projects_delivery: {
    operations: 'portfolio',
    project_portfolio: 'portfolio',
    portfolio: 'portfolio',
    delivery: 'portfolio',
    industry: 'industry_templates',
    industry_templates: 'industry_templates',
    construction: 'industry_templates',
    trading: 'industry_templates',
    manufacturing: 'industry_templates',
    service: 'industry_templates',
    procurement: 'industry_templates',
    logistics: 'industry_templates',
    admin: 'admin_ops',
    admin_ops: 'admin_ops',
    hr: 'admin_ops',
  },
  documents_approval: {
    approval: 'approvals',
    approvals: 'approvals',
    approval_workflow: 'approvals',
    documents: 'approvals',
    audit: 'audit',
    internal_audit: 'audit',
    audit_workspace: 'audit',
    evidence: 'evidence',
    audit_trail: 'evidence',
  },
  operations: {
    ideas_moat: 'product_studio',
    dev_hub: 'product_studio',
    tasks_progress: 'product_studio',
    roadmap: 'product_studio',
    deploy: 'logistics',
    supply_chain: 'logistics',
    procurement: 'logistics',
    campaign_lab: 'growth_marketing',
    campaign_funnel: 'growth_marketing',
    rollout_qa: 'growth_marketing',
    content_zalo: 'growth_marketing',
    video_creator: 'growth_marketing',
    video_lab: 'growth_marketing',
    market_research: 'growth_marketing',
    leads_outreach: 'sales_crm',
    ltv_nps: 'sales_crm',
    affiliate: 'sales_crm',
    pricing_lab: 'sales_crm',
  },
  analytics: {
    financial_charts: 'dashboard',
    observability: 'dashboard',
    ai_observability: 'dashboard',
    decision_memory: 'dashboard',
    market_research: 'simulations',
    market_survey: 'simulations',
    ml_applied: 'data_engineering',
    browser_sim: 'simulations',
    automation_planner: 'simulations',
    datascience: 'data_engineering',
    financial_ds: 'data_engineering',
    data_science: 'data_engineering',
    data_engineering: 'data_engineering',
    python_sql: 'ai_sandbox',
    python_sql_datascience: 'ai_sandbox',
    ai_game_studio: 'ai_sandbox',
    game_studio: 'ai_sandbox',
    game_ml: 'ai_sandbox',
    prompt_labs: 'ai_sandbox',
    prompt_lab: 'ai_sandbox',
    gemini_playground: 'ai_sandbox',
    gemini: 'ai_sandbox',
    deploy_business: 'simulations',
    deploy_lab: 'simulations',
    founder_labs: 'simulations',
    labs: 'ai_sandbox',
  },
  ai_factory: {
    overview: 'command',
    ai_ops: 'command',
    command_center: 'command',
    governance: 'governance',
    advanced: 'governance',
    agent_builder: 'builder',
    agent_assembly: 'builder',
    daemon: 'release',
    mobile: 'release',
    runtime: 'release',
    mission_queue: 'release',
    runbook: 'release',
    mission_templates: 'release',
    audit_trace: 'governance',
    mission_audit: 'governance',
    release_gate: 'release',
    release_ops: 'release',
    snapshot_export: 'release',
    review_notes: 'release',
    staff_roles: 'command',
    staff_assistants: 'command',
    agents: 'command',
    staff_assignment: 'command',
    assignment: 'command',
    people: 'command',
    memory_rag: 'builder',
    knowledge_content: 'builder',
    prompt_labs: 'command',
    robot_lab: 'automation',
    robot_auto: 'automation',
    automation_rules: 'automation',
    automations: 'automation',
    browser_sim: 'automation',
    robot_bridge: 'automation',
    automation_health: 'automation',
    tool_catalog: 'builder',
    skill_directory: 'builder',
    skill_invocation: 'builder',
    patch_review: 'release',
    patch_safety: 'release',
    labs_diagnostics: 'governance',
    openclaw: 'governance',
    tools_security: 'governance',
    security: 'governance',
    software_factory: 'automation',
    factory: 'automation',
    factory_runtime: 'automation',
    factory_health: 'automation',
    factory_commands: 'automation',
  },
  ai_staff_sandbox: {
    staff_assistants: 'agents',
    ai_ops: 'overview',
    robot_lab: 'automations',
    automation_rules: 'automations',
    prompt_labs: 'knowledge_prompts',
    project_memory: 'knowledge_prompts',
    python_sql: 'labs',
    browser_sim: 'automations',
    financial_ds: 'labs',
    ai_game_studio: 'labs',
    simulation: 'labs',
  },
  system_settings: {
    ai_gateway: 'general',
    integrations: 'integrations',
    connections: 'connectors',
    hybrid: 'connectors',
    hybrid_connectors: 'connectors',
    github: 'connectors',
    local_tools: 'connectors',
    web_ai: 'connectors',
    user_roles: 'general',
    permissions: 'general',
    audit: 'security',
    backup_data: 'general',
    security: 'security',
    config_health: 'connectors',
    rollback: 'recovery_ops',
    build_monitor: 'dev_ops',
    merge_readiness: 'dev_ops',
    pr_control: 'dev_ops',
    patch_diff: 'recovery_ops',
    patch_review: 'recovery_ops',
    sandbox_patch: 'recovery_ops',
    ci_recovery: 'recovery_ops',
    ci_run: 'recovery_ops',
    dev_handoff: 'dev_ops',
    ci_doctor: 'dev_ops',
    release_artifact: 'dev_ops',
    approved_pr: 'dev_ops',
    git_ops: 'dev_ops',
    git_assistant: 'dev_ops',
    approvals: 'dev_ops',
    artifact_inspector: 'dev_ops',
    backup_restore: 'general',
    emergency_stop: 'general',
    software_factory: 'dev_ops',
    release_factory: 'dev_ops',
    security_audit: 'security',
  },
};

export function resolveWorkspaceSubTab(
  workspaceId: string,
  requestedSubTabId: string | undefined,
  validSubTabIds: readonly string[],
): string | undefined {
  if (!requestedSubTabId) return undefined;
  if (validSubTabIds.includes(requestedSubTabId)) return requestedSubTabId;

  const alias = WORKSPACE_SUBTAB_ALIASES[workspaceId]?.[requestedSubTabId];
  if (alias && validSubTabIds.includes(alias)) return alias;

  return undefined;
}
