// Generator for gamePhysicsEngine.ts
import fs from 'fs';

const lines = [];
const w = (l) => lines.push(l);

w('/**');
w(' * gamePhysicsEngine.ts - Advanced 2D Physics Simulator');
w(' */');
w('');
w('export interface Vector2 { x: number; y: number; }');
w('export interface PhysicsBody { id: string; position: Vector2; velocity: Vector2; acceleration: Vector2; width: number; height: number; mass: number; isStatic: boolean; restitution: number; friction: number; tags: string[]; }');
w('export interface AABB { x: number; y: number; width: number; height: number; }');
w('export interface CollisionResult { overlap: boolean; penetrationX: number; penetrationY: number; normal: Vector2; }');
w('');
w('export function vec2(x: number, y: number): Vector2 { return { x, y }; }');
w('export function vecAdd(a: Vector2, b: Vector2): Vector2 { return { x: a.x + b.x, y: a.y + b.y }; }');
w('export function vecSub(a: Vector2, b: Vector2): Vector2 { return { x: a.x - b.x, y: a.y - b.y }; }');
w('export function vecLength(v: Vector2): number { return Math.sqrt(v.x * v.x + v.y * v.y); }');
w('export function vecScale(v: Vector2, s: number): Vector2 { return { x: v.x * s, y: v.y * s }; }');
w('');
w('export function aabbFromBody(body: PhysicsBody): AABB {');
w('  return { x: body.position.x - body.width / 2, y: body.position.y - body.height / 2, width: body.width, height: body.height };');
w('}');
w('export function aabbOverlap(a: AABB, b: AABB): boolean {');
w('  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;');
w('}');
w('');
w('export function createPhysicsBody(params: any): PhysicsBody {');
w('  return { id: params.id, position: params.position || { x: 0, y: 0 }, velocity: params.velocity || { x: 0, y: 0 },');
w('    acceleration: params.acceleration || { x: 0, y: 0 }, width: params.width || 32, height: params.height || 32,');
w('    mass: params.mass || 1, isStatic: params.isStatic || false, restitution: params.restitution ?? 0.5,');
w('    friction: params.friction ?? 0.1, tags: params.tags || [] };');
w('}');
w('');
w('export function updatePhysicsBody(body: PhysicsBody, dt: number, gravity?: number): void {');
w('  if (body.isStatic) return;');
w('  body.velocity.x += body.acceleration.x * dt;');
w('  body.velocity.y += (body.acceleration.y + (gravity || 0)) * dt;');
w('  body.velocity.x *= (1 - body.friction * dt);');
w('  if (Math.abs(body.velocity.x) < 0.01) body.velocity.x = 0;');
w('  body.position.x += body.velocity.x * dt;');
w('  body.position.y += body.velocity.y * dt;');
w('}');
w('');
w('export class SpatialHash {');
w('  private cellSize: number;');
w('  private cells: Map<string, PhysicsBody[]>;');
w('  constructor(cellSize = 64) { this.cellSize = cellSize; this.cells = new Map(); }');
w('  insert(body: PhysicsBody): void {');
w('    const aabb = aabbFromBody(body);');
w('    const minX = Math.floor(aabb.x / this.cellSize);');
w('    const maxX = Math.floor((aabb.x + aabb.width) / this.cellSize);');
w('    const minY = Math.floor(aabb.y / this.cellSize);');
w('    const maxY = Math.floor((aabb.y + aabb.height) / this.cellSize);');
w('    for (let cx = minX; cx <= maxX; cx++) {');
w('      for (let cy = minY; cy <= maxY; cy++) {');
w('        const key = cx + "," + cy;');
w('        if (!this.cells.has(key)) this.cells.set(key, []);');
w('        this.cells.get(key).push(body);');
w('      }');
w('    }');
w('  }');
w('  clear(): void { this.cells.clear(); }');
w('  getNearby(body: PhysicsBody): PhysicsBody[] {');
w('    const aabb = aabbFromBody(body);');
w('    const minX = Math.floor(aabb.x / this.cellSize);');
w('    const maxX = Math.floor((aabb.x + aabb.width) / this.cellSize);');
w('    const minY = Math.floor(aabb.y / this.cellSize);');
w('    const maxY = Math.floor((aabb.y + aabb.height) / this.cellSize);');
w('    const nearby = new Set<PhysicsBody>();');
w('    for (let cx = minX; cx <= maxX; cx++) {');
w('      for (let cy = minY; cy <= maxY; cy++) {');
w('        const key = cx + "," + cy;');
w('        const cell = this.cells.get(key);');
w('        if (cell) { for (const b of cell) { if (b !== body) nearby.add(b); } }');
w('      }');
w('    }');
w('    return Array.from(nearby);');
w('  }');
w('  get cellCount(): number { return this.cells.size; }');
w('}');
w('');
w('export function generateGameLoopCode(p: PhysicsBody, obstacles: PhysicsBody[], cw = 800, ch = 480): string {');
w('  const obsData = obstacles.map(o => ({ x: o.position.x, y: o.position.y, w: o.width, h: o.height }));');
w('  const code = [');
w("    'const canvas = document.getElementById(\"gameCanvas\");',");
w("    'const ctx = canvas.getContext(\"2d\");',");
w("    'canvas.width = ' + cw + ';',");
w("    'canvas.height = ' + ch + ';',");
w("    'let player = { x: ' + p.position.x + ', y: ' + p.position.y + ', w: ' + p.width + ', h: ' + p.height + ' };',");
w("    'let score = 0; let lives = 3; let keys = {}; let particles = [];',");
w("    'const obstacles = ' + JSON.stringify(obsData) + ';',");
w("    'document.addEventListener(\"keydown\", e => keys[e.key] = true);',");
w("    'document.addEventListener(\"keyup\", e => keys[e.key] = false);',");
w("    'function update(dt) {',");
w("    '  if (keys[\"ArrowLeft\"] || keys[\"a\"]) player.x -= 200 * dt;',");
w("    '  if (keys[\"ArrowRight\"] || keys[\"d\"]) player.x += 200 * dt;',");
w("    '  if (keys[\"ArrowUp\"] || keys[\"w\"]) player.y -= 200 * dt;',");
w("    '  if (keys[\"ArrowDown\"] || keys[\"s\"]) player.y += 200 * dt;',");
w("    '  player.x = Math.max(0, Math.min(canvas.width - player.w, player.x));',");
w("    '  player.y = Math.max(0, Math.min(canvas.height - player.h, player.y));',");
w("    '  for (const obs of obstacles) {',");
w("    '    if (player.x < obs.x + obs.w && player.x + player.w > obs.x &&',");
w("    '        player.y < obs.y + obs.h && player.y + player.h > obs.y) {',");
w("    '      score += 10;',");
w("    '      obs.x = Math.random() * (canvas.width - obs.w);',");
w("    '      obs.y = Math.random() * (canvas.height - obs.h);',");
w("    '    }',");
w("    '  }',");
w("    '  if (Math.random() < 0.3) {',");
w("    '    particles.push({ x: player.x + player.w/2, y: player.y + player.h/2, vx: (Math.random()-0.5)*100, vy: (Math.random()-0.5)*100, life: 1 });',");
w("    '  }',");
w("    '  for (let i = particles.length - 1; i >= 0; i--) {',");
w("    '    particles[i].x += particles[i].vx * dt;',");
w("    '    particles[i].y += particles[i].vy * dt;',");
w("    '    particles[i].life -= dt;',");
w("    '    if (particles[i].life <= 0) particles.splice(i, 1);',");
w("    '  }',");
w("    '}',");
w("    'function draw() {',");
w("    '  ctx.fillStyle = \"#0b0f19\";',");
w("    '  ctx.fillRect(0, 0, canvas.width, canvas.height);',");
w("    '  for (const obs of obstacles) {',");
w("    '    ctx.fillStyle = \"#06b6d4\"; ctx.shadowColor = \"#06b6d4\"; ctx.shadowBlur = 10;',");
w("    '    ctx.fillRect(obs.x, obs.y, obs.w, obs.h);',");
w("    '    ctx.shadowBlur = 0;',");
w("    '  }',");
w("    '  ctx.fillStyle = \"#3b82f6\"; ctx.shadowColor = \"#3b82f6\"; ctx.shadowBlur = 15;',");
w("    '  ctx.fillRect(player.x, player.y, player.w, player.h);',");
w("    '  ctx.shadowBlur = 0;',");
w("    '  for (const p of particles) {',");
w("    '    ctx.fillStyle = \"rgba(255, 100, 50, \" + p.life + \")\";',");
w("    '    ctx.beginPath(); ctx.arc(p.x, p.y, 3, 0, Math.PI * 2); ctx.fill();',");
w("    '  }',");
w("    '  ctx.fillStyle = \"#f8fafc\"; ctx.font = \"16px system-ui\";',");
w("    '  ctx.fillText(\"Score: \" + score, 16, 24);',");
w("    '  ctx.fillText(\"Lives: \" + lives, canvas.width - 100, 24);',");
w("    '}',");
w("    'let lastTime = 0;',");
w("    'function gameLoop(time) { const dt = Math.min((time - lastTime) / 1000, 0.05);',");
w("    '  lastTime = time; update(dt); draw(); requestAnimationFrame(gameLoop);',");
w("    '}',");
w("    'requestAnimationFrame(gameLoop);',");
w('  ];');
w('  return code.join("\\n");');
w('}');

fs.writeFileSync('server/services/gamePhysicsEngine.ts', lines.join('\n'), 'utf8');
console.log('Created gamePhysicsEngine.ts (' + lines.length + ' lines)');
