/**
 * apiTestGenerator.ts
 * ============================================================
 * API Test Generator — tự động sinh test suites cho
 * REST API endpoints, bao gồm happy path, edge cases,
 * và security tests.
 *
 * Output: Jest/Vitest/supertest test files
 */
import { randomUUID } from 'node:crypto';
import { dispatchTextThroughFabric } from './aiFabric';
import { scanDaemonRoutes } from './openApiGenerator';
import { appendAuditEvent } from './auditLog';
import fs from 'fs';
import path from 'path';

// ─── Types ──────────────────────────────────────────────────────────
export interface APIRoute {
  method: string;
  path: string;
  params: string[];
  description?: string;
}

export interface APITestCase {
  id: string;
  name: string;
  category: 'happy_path' | 'validation' | 'edge_case' | 'security' | 'error_handling';
  method: string;
  url: string;
  requestBody?: string;
  expectedStatus: number;
  expectedKeys: string[];
  description: string;
  autoGenerated: boolean;
}

export interface APITestSuite {
  id: string;
  name: string;
  target: string;
  routes: number;
  testCases: APITestCase[];
  testFramework: 'jest' | 'vitest';
  testCode: string;
  generatedAt: string;
  generationMs: number;
}

// ─── Storage ────────────────────────────────────────────────────────
const SUITES_DIR = path.join(process.cwd(), 'test_suites');
const INDEX_FILE = path.join(SUITES_DIR, '_index.json');

let suites: APITestSuite[] = [];

async function init(): Promise<void> {
  try {
    if (!fs.existsSync(SUITES_DIR)) await fs.promises.mkdir(SUITES_DIR, { recursive: true });
    if (fs.existsSync(INDEX_FILE)) suites = JSON.parse(await fs.promises.readFile(INDEX_FILE, 'utf8'));
  } catch { }
}
init().catch(() => undefined);

async function saveIndex(): Promise<void> { await fs.promises.writeFile(INDEX_FILE, JSON.stringify(suites, null, 2), 'utf8'); }

// ─── Test case generation ───────────────────────────────────────────

function generateTestCases(routes: APIRoute[]): APITestCase[] {
  const testCases: APITestCase[] = [];
  const sid = () => `tc_${randomUUID().slice(0, 8)}`;

  for (const route of routes) {
    const normalizedPath = route.path.replace(/:(\w+)/g, 'test-$1');
    const paramNames = route.params;

    // Happy path
    testCases.push({
      id: sid(), name: `[Happy] ${route.method} ${route.path} — success`,
      category: 'happy_path', method: route.method,
      url: `http://127.0.0.1:3001${normalizedPath}`,
      expectedStatus: route.method === 'POST' ? 201 : 200,
      expectedKeys: ['ok'],
      description: `${route.method} ${route.path} should return success.`,
      autoGenerated: true,
    });

    // Validation: missing body for POST/PATCH/PUT
    if (['POST', 'PATCH', 'PUT'].includes(route.method)) {
      testCases.push({
        id: sid(), name: `[Validation] ${route.method} ${route.path} — no body`,
        category: 'validation', method: route.method,
        url: `http://127.0.0.1:3001${normalizedPath}`,
        requestBody: '{}',
        expectedStatus: 400,
        expectedKeys: ['ok', 'error'],
        description: `Missing required fields should return 400.`,
        autoGenerated: true,
      });
    }

    // Edge case: invalid params
    if (paramNames.length > 0) {
      testCases.push({
        id: sid(), name: `[Edge] ${route.method} ${route.path} — invalid param`,
        category: 'edge_case', method: route.method,
        url: `http://127.0.0.1:3001${route.path.replace(/:(\w+)/g, 'INVALID%20%23%24%5E')}`,
        expectedStatus: 400,
        expectedKeys: ['ok'],
        description: `Invalid path parameters should be handled gracefully.`,
        autoGenerated: true,
      });
    }

    // Security: SQL injection attempt in query params
    if (route.path.includes(':')) {
      testCases.push({
        id: sid(), name: `[Security] ${route.method} ${route.path} — SQL injection`,
        category: 'security', method: route.method,
        url: `http://127.0.0.1:3001${route.path.replace(/:(\w+)/g, "' OR '1'='1")}`,
        expectedStatus: 400,
        expectedKeys: ['ok'],
        description: `SQL injection attempt should not succeed.`,
        autoGenerated: true,
      });
    }

    // Error handling: invalid HTTP method
    if (route.method !== 'GET') {
      testCases.push({
        id: sid(), name: `[Error] ${route.method} ${route.path} — wrong method`,
        category: 'error_handling', method: 'GET',
        url: `http://127.0.0.1:3001${normalizedPath}`,
        expectedStatus: 404,
        expectedKeys: [],
        description: `Using wrong HTTP method should return appropriate error.`,
        autoGenerated: true,
      });
    }
  }

  return testCases;
}

function generateTestCode(suite: APITestSuite): string {
  const BASE_URL = 'http://127.0.0.1:3001';
  let code = `// Auto-generated API test suite: ${suite.name}
// Target: ${suite.target}
// Generated: ${suite.generatedAt}
// Framework: ${suite.testFramework}
// Routes tested: ${suite.routes}
// Test cases: ${suite.testCases.length}

`;

  if (suite.testFramework === 'vitest') {
    code += `import { describe, it, expect, beforeAll, afterAll } from 'vitest';\n\n`;
  } else {
    code += `const request = require('supertest');\n\n`;
  }

  code += `\nconst BASE_URL = '${BASE_URL}';\n\n`;

  // Group by route
  const byRoute = new Map<string, APITestCase[]>();
  for (const tc of suite.testCases) {
    const key = `${tc.method} ${tc.url.split('?')[0]}`;
    if (!byRoute.has(key)) byRoute.set(key, []);
    byRoute.get(key)!.push(tc);
  }

  for (const [, testCases] of byRoute) {
    const first = testCases[0];
    code += `describe('${first.method} ${first.url.replace(BASE_URL, '')}', () => {\n`;

    for (const tc of testCases) {
      code += `  it('${tc.name}', async () => {\n`;
      code += `    const response = await fetch('${tc.url}', {\n`;
      code += `      method: '${tc.method}',\n`;
      code += `      headers: { 'Content-Type': 'application/json' }${tc.requestBody ? `,\n      body: '${tc.requestBody}'` : ''}\n`;
      code += `    });\n`;
      code += `    expect(response.status).toBe(${tc.expectedStatus});\n`;

      if (tc.expectedKeys.length > 0) {
        code += `    const data = await response.json();\n`;
        for (const key of tc.expectedKeys) {
          code += `    expect(data).toHaveProperty('${key}');\n`;
        }
      }

      code += `  });\n\n`;
    }
    code += `});\n\n`;
  }

  return code;
}

// ─── Core API ───────────────────────────────────────────────────────

export async function generateAPITestSuite(
  name: string,
  sourceFile: string,
  options?: { framework?: 'jest' | 'vitest'; maxRoutes?: number },
): Promise<APITestSuite> {
  const started = Date.now();
  const suiteId = `apit_${Date.now()}`;

  // Scan routes from daemon source
  const routes = scanDaemonRoutes(sourceFile).slice(0, options?.maxRoutes || 30);

  // Generate test cases (heuristic)
  let testCases = generateTestCases(routes);

  // AI supplement for complex routes
  if (routes.length > 0) {
    try {
      const aiPrompt = `Review these API routes and suggest additional test cases (edge cases, security tests) the heuristic might have missed:

ROUTES:
${routes.slice(0, 10).map(r => `${r.method} ${r.path}${r.description ? ` — ${r.description}` : ''}`).join('\n')}

Return format, one per line:
ADD_TEST: [method] | [url] | [category:happy_path/validation/edge_case/security/error_handling] | [expectedStatus] | [description]

If no additional tests needed, return: NO_ADDITIONAL.`;

      const result = await dispatchTextThroughFabric(aiPrompt, undefined, { domain: 'general', localFallback: true });
      if (result.winner?.contentPreview) {
        const lines = result.winner.contentPreview.split('\n').filter(l => l.toUpperCase().startsWith('ADD_TEST:'));
        for (const line of lines.slice(0, 5)) {
          const parts = line.replace(/^ADD_TEST:\s*/i, '').split('|').map(s => s.trim());
          if (parts.length >= 4) {
            testCases.push({
              id: `tc_ai_${randomUUID().slice(0, 6)}`,
              name: `[AI] ${parts[0]} ${parts[1]?.slice(0, 40)}`,
              category: (parts[2] as APITestCase['category']) || 'edge_case',
              method: parts[0], url: `http://127.0.0.1:3001${parts[1] || ''}`,
              expectedStatus: parseInt(parts[3]) || 400,
              expectedKeys: ['ok'],
              description: parts[4] || '',
              autoGenerated: true,
            });
          }
        }
      }
    } catch { }
  }

  const suite: APITestSuite = {
    id: suiteId, name, target: sourceFile,
    routes: routes.length, testCases,
    testFramework: options?.framework || 'vitest',
    testCode: '',
    generatedAt: new Date().toISOString(),
    generationMs: 0,
  };

  suite.testCode = generateTestCode(suite);
  suite.generationMs = Date.now() - started;

  // Save to file
  const fileName = `${name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.test.ts`;
  const filePath = path.join(SUITES_DIR, fileName);
  await fs.promises.writeFile(filePath, suite.testCode, 'utf8');

  suites.push(suite);
  saveIndex().catch(() => undefined);

  await appendAuditEvent({
    actor: 'system', workspace: 'API Test Generator', action: 'tests.generate',
    target: name, risk: 'LOW', status: 'executed',
    summary: `Generated test suite: ${testCases.length} cases for ${routes.length} routes`,
    connectorId: 'api-test-generator',
    evidence: { suiteId, routes: routes.length, testCases: testCases.length },
  }).catch(() => undefined);

  return suite;
}

export function getSuite(id: string): APITestSuite | undefined { return suites.find(s => s.id === id); }
export function listSuites(): APITestSuite[] { return [...suites].reverse(); }
export function getTestStats(): { totalSuites: number; totalTestCases: number; avgTestsPerSuite: number } {
  return {
    totalSuites: suites.length,
    totalTestCases: suites.reduce((s, suite) => s + suite.testCases.length, 0),
    avgTestsPerSuite: suites.length > 0 ? Math.round(suites.reduce((s, suite) => s + suite.testCases.length, 0) / suites.length) : 0,
  };
}
