/**
 * contextualDocGenerator.ts
 * ============================================================
 * Contextual Documentation Generator — AI đọc codebase
 * và sinh README, API docs, architecture docs, examples.
 */
import { randomUUID } from 'node:crypto';
import { dispatchTextThroughFabric } from './aiFabric';
import { searchCodebase } from './localSearchService';
import { appendAuditEvent } from './auditLog';
import fs from 'fs';
import path from 'path';

// ─── Types ──────────────────────────────────────────────────────────
export type DocType = 'readme' | 'api_docs' | 'architecture' | 'usage_guide' | 'contributing' | 'changelog';

export interface DocSection {
  title: string;
  content: string;
  autoGenerated: boolean;
}

export interface GeneratedDoc {
  id: string;
  type: DocType;
  title: string;
  target: string;
  sections: DocSection[];
  format: 'markdown' | 'html';
  content: string;
  filePath: string;
  generatedAt: string;
  generationMs: number;
}

// ─── Storage ────────────────────────────────────────────────────────
const DOCS_DIR = path.join(process.cwd(), 'docs', 'auto-generated');
let documents: GeneratedDoc[] = [];

async function init(): Promise<void> {
  try {
    if (!fs.existsSync(DOCS_DIR)) await fs.promises.mkdir(DOCS_DIR, { recursive: true });
  } catch { }
}
init().catch(() => undefined);

// ─── Core API ───────────────────────────────────────────────────────

export async function generateDocumentation(
  docType: DocType,
  target: string,
  options?: { maxFiles?: number; format?: 'markdown' | 'html' },
): Promise<GeneratedDoc> {
  const docId = `doc_${Date.now()}_${randomUUID().slice(0, 6)}`;
  const started = Date.now();
  const sections: DocSection[] = [];

  // Gather context
  const codeFiles = await searchCodebase('service', options?.maxFiles || 15);
  let codeContext = '';
  for (const file of codeFiles.slice(0, options?.maxFiles || 10)) {
    const fp = path.join(process.cwd(), file.relativePath);
    if (fs.existsSync(fp)) {
      try {
        const content = fs.readFileSync(fp, 'utf8');
        const exports = content.match(/export\s+(?:async\s+)?(?:function|class|const|interface|type)\s+(\w+)/g) || [];
        codeContext += `\n### ${file.relativePath}\nExports: ${exports.join(', ')}\n`;
      } catch { }
    }
  }

  // Build prompt based on doc type
  let prompt = '';
  let title = '';

  switch (docType) {
    case 'readme':
      title = 'README';
      prompt = `Generate a comprehensive README.md for this project:

Project: ${target}
${codeContext}

Sections:
## Overview — What this project does
## Features — Key capabilities
## Architecture — High-level design
## Getting Started — Setup instructions
## Usage — How to use
## API Reference — Key endpoints
## Contributing — How to contribute
## License`;

      break;

    case 'api_docs':
      title = 'API Documentation';
      prompt = `Generate API documentation for this project:

Target: ${target}
${codeContext}

Document key API endpoints with:
- Endpoint path and method
- Request/Response examples
- Parameters
- Error codes`;

      break;

    case 'architecture':
      title = 'Architecture Overview';
      prompt = `Generate an architecture document for this project:

Target: ${target}
${codeContext}

Cover:
- High-level architecture diagram description
- Key services and their responsibilities
- Data flow
- Technology stack
- Design decisions`;

      break;

    case 'usage_guide':
      title = 'Usage Guide';
      prompt = `Generate a usage guide with practical examples.

Target: ${target}
${codeContext}

Include: code examples, common use cases, troubleshooting tips.`;

      break;

    case 'contributing':
      title = 'Contributing Guide';
      prompt = `Generate a CONTRIBUTING.md for this project.

Target: ${target}

Cover: setup, code style, PR process, testing, commit conventions.`;

      break;

    case 'changelog':
      title = 'Changelog';
      prompt = `Generate a changelog based on recent changes.

Target: ${target}

Format: version, date, changes in categories (Added, Changed, Fixed, Removed).`;

      break;
  }

  // Generate with AI
  let content = '';
  try {
    const result = await dispatchTextThroughFabric(prompt, undefined, { domain: 'general', localFallback: true });
    if (result.winner?.contentPreview) {
      content = result.winner.contentPreview;

      // Parse sections from markdown headers
      const sectionRegex = /^##\s+(.+)$/gm;
      let match: RegExpExecArray | null;
      let lastIdx = 0;
      while ((match = sectionRegex.exec(content)) !== null) {
        if (lastIdx > 0) {
          sections.push({
            title: content.slice(lastIdx, match.index).trim().split('\n')[0].replace(/^##\s+/, ''),
            content: content.slice(lastIdx, match.index).trim(),
            autoGenerated: true,
          });
        }
        lastIdx = match.index;
      }
      if (lastIdx > 0 && lastIdx < content.length) {
        sections.push({
          title: content.slice(lastIdx).trim().split('\n')[0].replace(/^##\s+/, ''),
          content: content.slice(lastIdx).trim(),
          autoGenerated: true,
        });
      }
    }
  } catch { /* fallback */ }

  if (!content) {
    content = `# ${title}\n\nAuto-generated documentation for ${target}.\n\n${codeContext}`;
  }

  if (sections.length === 0) {
    sections.push({ title, content: content.slice(0, 500), autoGenerated: true });
  }

  // Save to file
  const fileName = `${docType}_${new Date().toISOString().slice(0, 10)}.md`;
  const filePath = path.join(DOCS_DIR, fileName);
  await fs.promises.writeFile(filePath, content, 'utf8');

  const doc: GeneratedDoc = {
    id: docId, type: docType, title, target,
    sections, format: options?.format || 'markdown',
    content, filePath,
    generatedAt: new Date().toISOString(),
    generationMs: Date.now() - started,
  };

  documents.push(doc);

  await appendAuditEvent({
    actor: 'system', workspace: 'Doc Generator', action: 'doc.generate',
    target, risk: 'LOW', status: 'executed',
    summary: `Generated ${docType}: ${sections.length} sections`,
    connectorId: 'doc-generator',
    evidence: { docId, type: docType, sections: sections.length },
  }).catch(() => undefined);

  return doc;
}

export function getDoc(id: string): GeneratedDoc | undefined { return documents.find(d => d.id === id); }
export function listDocs(): GeneratedDoc[] { return [...documents].reverse(); }
export function getDocTypes(): DocType[] { return ['readme', 'api_docs', 'architecture', 'usage_guide', 'contributing', 'changelog']; }
