/**
 * server/services/dormantServicesRouter.ts
 * ============================================================
 * Hub router — delegates to domain routers under ./dormant/.
 * Generated by tools/split-dormant-router.mjs (read-only split).
 */

import type { Express } from 'express';
import { registerDevopsRoutes } from './dormant/devopsRouter.ts';
import { registerIntegrationsRoutes } from './dormant/integrationsRouter.ts';
import { registerEnterpriseAutonomyRoutes } from './dormant/enterprise-autonomyRouter.ts';
import { registerAiKnowledgeRoutes } from './dormant/ai-knowledgeRouter.ts';
import { registerFinanceAccountingRoutes } from './dormant/finance-accountingRouter.ts';
import { registerSalesMarketingRoutes } from './dormant/sales-marketingRouter.ts';

export function registerDormantServicesRoutes(app: Express): void {
  registerDevopsRoutes(app);
  registerIntegrationsRoutes(app);
  registerEnterpriseAutonomyRoutes(app);
  registerAiKnowledgeRoutes(app);
  registerFinanceAccountingRoutes(app);
  registerSalesMarketingRoutes(app);
}
