/**
 * server/services/operatingRhythmScheduler.ts
 * ============================================================
 * Company Operating Rhythm & Automated Executive Calendar Engine
 *
 * Implements automated scheduling for:
 * 1. Daily Morning Standup (08:00)
 * 2. Weekly Executive Retrospective & Resource Rebalancing (Friday 16:00)
 * 3. Monthly Financial & Tax Closing (5th of every month)
 * 4. Quarterly Strategic OKR Recalibration
 */

export interface OperatingRhythmEvent {
  id: string;
  title: string;
  type: 'daily_standup' | 'weekly_review' | 'monthly_close' | 'quarterly_okr' | 'tax_deadline';
  scheduledTime: string; // ISO String or cron description
  recurringPattern: 'daily' | 'weekly' | 'monthly' | 'quarterly';
  assignedRoles: string[];
  status: 'upcoming' | 'in_progress' | 'completed';
  agendaItems: string[];
  autoGeneratedReportUrl?: string;
}

let rhythmScheduleStore: OperatingRhythmEvent[] = [
  {
    id: 'rhythm_1',
    title: 'Daily AI CEO Standup & Blocker Clearance',
    type: 'daily_standup',
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    recurringPattern: 'daily',
    assignedRoles: ['CEO', 'AI Sales Lead', 'AI CFO', 'AI DevOps'],
    status: 'upcoming',
    agendaItems: [
      'Đánh giá 14 blocker đã được tự động xử lý',
      'Kiểm tra tiến độ chốt 3 deal Enterprise trong pipeline',
      'Xác nhận trạng thái xanh của CI/CD Desktop Release',
    ],
  },
  {
    id: 'rhythm_2',
    title: 'Weekly Multi-Factory Throughput & Quality Review',
    type: 'weekly_review',
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    recurringPattern: 'weekly',
    assignedRoles: ['CEO', 'Factory Production Lead', 'Quality Gate Inspector'],
    status: 'upcoming',
    agendaItems: [
      'Đo lường sản lượng 4 nhà máy (SWE, Video, Game, Marketing)',
      'Phân tích 3 điểm nghẽn hiệu năng trong pipeline lập trình tự động',
      'Duyệt kế hoạch phát hành phiên bản Desktop tiếp theo',
    ],
  },
  {
    id: 'rhythm_3',
    title: 'Hạn nộp Tờ khai thuế GTGT Q3/2026 (TT80)',
    type: 'tax_deadline',
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 120).toISOString(),
    recurringPattern: 'quarterly',
    assignedRoles: ['AI CFO & Tax Specialist', 'CEO'],
    status: 'upcoming',
    agendaItems: [
      'Xuất bản XML Tờ khai 01/GTGT theo đúng chuẩn Tổng cục Thuế',
      'Ghi nhận chi phí được khấu trừ hợp lệ và áp dụng ưu đãi thuế phần mềm 50%',
      'Ký số phê duyệt nộp thuế điện tử qua eTax',
    ],
  },
  {
    id: 'rhythm_4',
    title: 'Monthly Financial Close & P&L Variance Review',
    type: 'monthly_close',
    scheduledTime: new Date(Date.now() + 1000 * 60 * 60 * 240).toISOString(),
    recurringPattern: 'monthly',
    assignedRoles: ['AI CFO', 'CEO'],
    status: 'upcoming',
    agendaItems: [
      'Đối soát 100% sao kê ngân hàng với các hóa đơn đã xuất',
      'Tính toán Runway thực tế và mô phỏng chi phí tháng kế tiếp',
      'Đánh giá hiệu quả ROI của từng AI Agent trong công ty',
    ],
  },
];

/**
 * Lấy danh sách toàn bộ lịch vận hành công ty
 */
export function getCompanyOperatingSchedule(): OperatingRhythmEvent[] {
  return rhythmScheduleStore;
}

/**
 * Thêm một sự kiện vận hành mới
 */
export function scheduleOperatingEvent(event: Omit<OperatingRhythmEvent, 'id' | 'status'>): OperatingRhythmEvent {
  const newEvent: OperatingRhythmEvent = {
    id: `rhythm_${Date.now()}`,
    status: 'upcoming',
    ...event,
  };
  rhythmScheduleStore.push(newEvent);
  return newEvent;
}

/**
 * Đánh dấu một sự kiện vận hành là hoàn thành
 */
export function completeOperatingEvent(id: string): boolean {
  const event = rhythmScheduleStore.find((e) => e.id === id);
  if (event) {
    event.status = 'completed';
    return true;
  }
  return false;
}
