/**
 * vscode-context-exporter.ts
 * ============================================================
 * Exports AI session data in formats compatible with:
 *  - VS Code (GitHub Copilot Chat context)
 *  - Cursor (cursor.sh context files)
 *  - Continue.dev (open-source VS Code AI extension)
 *  - Generic .context.json format
 *
 * Usage:
 *   Called from /api/edit and /api/apply responses,
 *   or directly via CLI: ai-assistant export <file>
 * ============================================================
 */

import fs from "fs";
import path from "path";
import type { FileContext } from "./safeFileManager";
import type { ExtractedCode } from "./codingContext";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ExportFormat = "cursor" | "copilot" | "continue" | "generic";

export interface ContextExportInput {
  instruction: string;
  files: FileContext[];
  primaryCode?: ExtractedCode;
  explanation?: string;
  modelUsed?: string;
  diff?: string;
  workspaceRoot: string;
}

export interface ContextExportResult {
  format: ExportFormat;
  outputPath: string;
  sizeBytes: number;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Export context to a file usable by VS Code / Cursor / Continue.dev.
 *
 * @param input   The session data (files, AI suggestions, explanation)
 * @param format  Target editor format
 * @param outDir  Where to write the output file (defaults to workspace root)
 */
export async function exportContext(
  input: ContextExportInput,
  format: ExportFormat = "generic",
  outDir?: string
): Promise<ContextExportResult> {
  const targetDir = outDir ?? path.join(input.workspaceRoot, ".ai_context");
  await fs.promises.mkdir(targetDir, { recursive: true });

  let content: string;
  let fileName: string;

  switch (format) {
    case "cursor":
      ({ content, fileName } = buildCursorContext(input));
      break;
    case "copilot":
      ({ content, fileName } = buildCopilotContext(input));
      break;
    case "continue":
      ({ content, fileName } = buildContinueContext(input));
      break;
    default:
      ({ content, fileName } = buildGenericContext(input));
  }

  const outputPath = path.join(targetDir, fileName);
  await fs.promises.writeFile(outputPath, content, "utf-8");

  const stat = await fs.promises.stat(outputPath);
  return { format, outputPath, sizeBytes: stat.size };
}

/**
 * Export a unified diff suitable for patch/apply tools.
 * Returns the diff string and optionally writes to file.
 */
export function generateUnifiedDiff(
  originalContent: string,
  newContent: string,
  filePath: string
): string {
  const originalLines = originalContent.split("\n");
  const newLines = newContent.split("\n");

  const hunks = computeDiffHunks(originalLines, newLines);
  if (hunks.length === 0) return "";

  const header = `--- a/${filePath}\n+++ b/${filePath}\n`;
  return header + hunks.join("\n");
}

/**
 * Write a .vscode-context file for Copilot Chat's "Attach Context" feature.
 * This is a simplified markdown-based format Copilot can read.
 */
export function buildCopilotMarkdown(
  input: ContextExportInput
): string {
  const parts: string[] = [
    "# AI Coding Context",
    "",
    `**Instruction:** ${input.instruction}`,
    "",
  ];

  if (input.modelUsed) {
    parts.push(`**Generated by:** ${input.modelUsed}`, "");
  }

  for (const file of input.files) {
    parts.push(
      `## ${file.relativePath}`,
      `> ${file.language} | ${file.sizeBytes} bytes`,
      "",
      "```" + file.language,
      file.content,
      "```",
      ""
    );
  }

  if (input.primaryCode) {
    parts.push(
      "## AI Suggested Code",
      "",
      input.explanation ?? "",
      "",
      "```" + input.primaryCode.language,
      input.primaryCode.code,
      "```",
      ""
    );
  }

  if (input.diff) {
    parts.push("## Diff", "", "```diff", input.diff, "```", "");
  }

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Format builders
// ---------------------------------------------------------------------------

function buildGenericContext(input: ContextExportInput): { content: string; fileName: string } {
  const payload = {
    version: 1,
    format: "ai-coding-assistant",
    generatedAt: new Date().toISOString(),
    workspaceRoot: input.workspaceRoot,
    instruction: input.instruction,
    modelUsed: input.modelUsed,
    files: input.files.map((f) => ({
      path: f.relativePath,
      language: f.language,
      content: f.content,
    })),
    suggestedCode: input.primaryCode
      ? {
          language: input.primaryCode.language,
          code: input.primaryCode.code,
          targetFile: input.primaryCode.targetFile,
        }
      : null,
    explanation: input.explanation ?? null,
    diff: input.diff ?? null,
  };

  return {
    content: JSON.stringify(payload, null, 2),
    fileName: `context_${Date.now()}.context.json`,
  };
}

function buildCursorContext(input: ContextExportInput): { content: string; fileName: string } {
  // Cursor's context format: JSON with messages array (OpenAI chat format)
  const messages = [
    {
      role: "system",
      content: `You are an AI coding assistant. The user is working on: ${input.workspaceRoot}`,
    },
    ...input.files.map((f) => ({
      role: "user",
      content: `File: ${f.relativePath}\n\`\`\`${f.language}\n${f.content}\n\`\`\``,
    })),
    {
      role: "user",
      content: input.instruction,
    },
  ];

  if (input.primaryCode) {
    messages.push({
      role: "assistant",
      content: `${input.explanation ?? ""}\n\n\`\`\`${input.primaryCode.language}\n${input.primaryCode.code}\n\`\`\``,
    });
  }

  const payload = {
    version: 1,
    format: "cursor",
    messages,
    context: {
      files: input.files.map((f) => ({
        path: f.relativePath,
        language: f.language,
      })),
    },
  };

  return {
    content: JSON.stringify(payload, null, 2),
    fileName: `cursor_context_${Date.now()}.json`,
  };
}

function buildCopilotContext(input: ContextExportInput): { content: string; fileName: string } {
  // GitHub Copilot Chat: markdown format for "Attach Context"
  const content = buildCopilotMarkdown(input);
  return {
    content,
    fileName: `copilot_context_${Date.now()}.md`,
  };
}

function buildContinueContext(input: ContextExportInput): { content: string; fileName: string } {
  // Continue.dev context format
  const payload = {
    version: 1,
    format: "continue",
    title: input.instruction.slice(0, 80),
    description: input.explanation ?? input.instruction,
    context: input.files.map((f) => ({
      name: f.relativePath,
      description: `${f.language} file`,
      content: f.content,
    })),
    suggestedEdit: input.primaryCode
      ? {
          filepath: input.primaryCode.targetFile ?? input.files[0]?.relativePath,
          newContent: input.primaryCode.code,
        }
      : undefined,
  };

  return {
    content: JSON.stringify(payload, null, 2),
    fileName: `continue_context_${Date.now()}.json`,
  };
}

// ---------------------------------------------------------------------------
// Minimal diff computation (LCS-based for small files)
// ---------------------------------------------------------------------------

function computeDiffHunks(originalLines: string[], newLines: string[]): string[] {
  // For large files, use a simple line-by-line comparison
  const MAX_LINES_FOR_FULL_DIFF = 500;

  if (originalLines.length > MAX_LINES_FOR_FULL_DIFF || newLines.length > MAX_LINES_FOR_FULL_DIFF) {
    // Simplified diff: just show full replacement
    return [
      `@@ -1,${originalLines.length} +1,${newLines.length} @@`,
      ...originalLines.map((l) => `-${l}`),
      ...newLines.map((l) => `+${l}`),
    ];
  }

  // Myers diff algorithm (simplified)
  const lcs = computeLCS(originalLines, newLines);
  const hunks: string[] = [];
  let oIdx = 0;
  let nIdx = 0;
  let lIdx = 0;

  const CONTEXT_LINES = 3;
  let currentHunk: string[] = [];
  let hunkStart = { o: 1, n: 1 };
  let inHunk = false;

  const flushHunk = (): void => {
    if (currentHunk.length > 0) {
      const oCount = currentHunk.filter((l) => !l.startsWith("+")).length;
      const nCount = currentHunk.filter((l) => !l.startsWith("-")).length;
      hunks.push(`@@ -${hunkStart.o},${oCount} +${hunkStart.n},${nCount} @@`);
      hunks.push(...currentHunk);
      currentHunk = [];
    }
  };

  while (oIdx < originalLines.length || nIdx < newLines.length) {
    if (
      lIdx < lcs.length &&
      oIdx < originalLines.length &&
      nIdx < newLines.length &&
      originalLines[oIdx] === lcs[lIdx] &&
      newLines[nIdx] === lcs[lIdx]
    ) {
      // Common line
      if (inHunk) {
        currentHunk.push(` ${originalLines[oIdx]}`);
      }
      oIdx++;
      nIdx++;
      lIdx++;
    } else if (oIdx < originalLines.length && (lIdx >= lcs.length || originalLines[oIdx] !== lcs[lIdx])) {
      if (!inHunk) {
        inHunk = true;
        hunkStart = { o: oIdx + 1, n: nIdx + 1 };
      }
      currentHunk.push(`-${originalLines[oIdx]}`);
      oIdx++;
    } else if (nIdx < newLines.length) {
      if (!inHunk) {
        inHunk = true;
        hunkStart = { o: oIdx + 1, n: nIdx + 1 };
      }
      currentHunk.push(`+${newLines[nIdx]}`);
      nIdx++;
    }
  }

  flushHunk();
  return hunks;
}

function computeLCS(a: string[], b: string[]): string[] {
  const m = a.length;
  const n = b.length;
  const dp = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));

  for (let i = 1; i <= m; i++) {
    for (let j = 1; j <= n; j++) {
      if (a[i - 1] === b[j - 1]) {
        dp[i][j] = dp[i - 1][j - 1] + 1;
      } else {
        dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
      }
    }
  }

  // Backtrack
  const result: string[] = [];
  let i = m;
  let j = n;
  while (i > 0 && j > 0) {
    if (a[i - 1] === b[j - 1]) {
      result.unshift(a[i - 1]);
      i--;
      j--;
    } else if (dp[i - 1][j] > dp[i][j - 1]) {
      i--;
    } else {
      j--;
    }
  }

  return result;
}
